
#ifndef SELF_MODULE_ID
#define SELF_MODULE_ID

enum TASK_MODULE_ID	// 任务模块的 ID
{
	MODULE_ID_MY_LOGIC = 1,
	MODULE_ID_OTHER_LOGIC = 2,
	MODULE_ID_DB_MY_NAME = 3,
};

#define TIMER_ID_TEST_01 1
#define TIMER_ID_TEST_02 2

#define MAIN_TEST_USER_INFO 10
#define SUB_TEST_USER_INFO 101

//add by Ivan_han 20130313
#define SUB_SINGLE_USER_INFO_REQ 102
#define SUB_SINGLE_USER_INFO_SUCCEED 103
#define SUB_SINGLE_USER_INFO_FAILD 104

#endif
