void hi();
int test_so_func(int a,int b);
int do_test_so_func(int a,int b);
double lcoss(double x);
double lsinn(double x);
double lexpp(double x);
double bsdet(double *a,int n);
void brmul(double *a,double *b,int m,int n,int k,double *c);
int brinv(double *a,int n);
void phbub(char **p,int n,int k,int m);
void phhap(char **p,int n,int k,int m);
void phqck(char **p,int n,int k,int m);
void phshl(char **p,int n,int k,int m);
int qhbsh(char **p,int n,char *a,char *b,int *m);
void pcbub(char *p,int n);
void pchap(char *p,int n);
void pcqck(char *p,int n);
void pcshl(char *p,int n);
void pibub(int *p,int n);
void pihap(int *p,int n);
void piqck(int *p,int n);
void pishl(int *p,int n);
void prbub(double *p,int n);
void prhap(double *p,int n);
void prqck(double *p,int n);
void prshl(double *p,int n);
void ptopo(int n,int *r,int m,int *p);
int qibsh(int *p,int n,int a,int b,int *m);
int qrbsh(double *p,int n,double a,double b,int *m);
